Unsupervised Learning  
K-Means Algorithm  
1. Initialize Clusters (Randomly)  
2. Cluster Assignment  
3. Move Cluster  

Dimensionality Reduction  
Purposes  
1. Data Compression
2. Visualization
3. Speed Up Algorithm

Try your algorithm without dimensionality reduction first, then use it if you need it.

Principle Components Analysis  
1. Preprocess Data (Subtract the mean, then divide by range)
2. Compute Covariance Matrix (```1 / m * np.dot(X.T, X)``` or ```cov(X)``` want a $\mathbb{R}^{n \times n}$ matrix)
3. Compute the eigenvectors of the covariance (```eig(X)``` or ```u, s, v = svd(X)```)
4. Take the first k eigenvalues of the U matrix and compute z (```Z = np.dot(X, U_reduce)```)  
To calculate the original x, ```X = np.dot(np.dot(Z, U_reduce.T))```

Choosing Number of Principle Components  
Have a threshold for retained variance  
Calculate the variance retained by $\frac{sum_{i=1}^k S_{ii}}{sum_{i=1}^n S_{ii}}$  
If the threshold is 99%, then the value about should be greater than 0.99



    

In [3]:
import numpy as np
import random

In [43]:
#randomly pick k points from the training set
def initialize_centroids(K, X):
    ids = random.sample(range(X.shape[0]), K)
    centroids = []
    for i in ids:
        centroids.append(np.array(X[i]))
    centroids = np.array(centroids)
    return centroids
X = np.array([[1, 2], [3, 3], [5, 6], [7, 8]])
centroids = initialize_centroids(2, X)

In [44]:
#assign an id to each x
def assign_clusters(clusters, X):
    idx = np.zeros(X.shape[0])
    for i in range(X.shape[0]):
        min_dist = float("inf")
        best_c = 0
        for c in range(len(clusters)):
            dist = np.sum((clusters[c] - X[i]) ** 2)
            if dist < min_dist:
                best_c = c
                min_dist = dist
        idx[i] = best_c
    return idx
idx = assign_clusters(centroids, X)
print(centroids)
print(idx)

[[5 6]
 [7 8]]
[0. 0. 0. 1.]


In [45]:
def move_centroids(clusters, idx, X): 
    for c in range(clusters.shape[1]):
        centroid_mean = np.zeros((1, clusters.shape[1]))
        count = 0
        for i in range(len(idx)):
            if (idx[i] == c):
                centroid_mean = centroid_mean + X[i]
                count += 1
        clusters[c] = centroid_mean / count
    return clusters
print(centroids)
clusters = move_centroids(centroids, idx, X)
print(clusters)

[[5 6]
 [7 8]]
[[3 3]
 [7 8]]


In [67]:
def kmeans(K, X, num_iters):
    centroids = initialize_centroids(K, X)
    for i in range(num_iters):
        idx = assign_clusters(clusters, X)
        centroids = move_centroids(clusters, idx, X)
    return centroids, idx
kmeans(2, np.array([[1, 2], [3, 3], [5, 6], [7, 8]]), 4)

(array([[6, 7],
        [2, 2]]), array([1., 1., 0., 0.]))

In [1]:
def PCA(X, K):
    Cov = 1 / m * np(X.T, X)
    U, S, V = svd(Cov)
    U_reduce = U[:, 1:K]
    Z = np.dot(X, U_reduce)
    X_rec = np.dot(Z, U_reduce.T)
    return Z, X_rec